### ISSUE TITLE
Fake-ssh port number

### ISSUE THREAD

**Issue by sandweel** [cheeseandcereal/fake-ssh#2]
Hello.
Thank you for this awesome script :)

For best usage recommend to add possibility to specify port number as flag or argument like below:

**./fake_ssh.py 2022
./fake_ssh.py -p 2022**

**Comment by cheeseandcereal** [comment]
Yeah sure. I just wrote this over an evening a while ago for a red/blue team event, so the code is not very clean, haha.

Added support to supply an optional port and bind address with 668d8620be0ad3c57e7e4fea8bd2925cc779e265 which is on the `master` branch now
